### ISSUE TITLE
Username/Password auth error

### ISSUE THREAD

**Issue by juliemturner** [s-KaiNet/vscode-sp-typed-item#2]
Decided to give the extension a try today and used the "Username/Password" method for SharePoint online and get the following error:

Error: Unknown cipher
	at Cipheriv.createCipherBase (internal/crypto/cipher.js:79:18)
	at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:20)
	at new Cipheriv (internal/crypto/cipher.js:225:22)
	at Object.createCipheriv (crypto.js:105:10)
	at Object.encrypt (c:\Users\jturner.BMA\.vscode\extensions\s-kainet.sharepoint-typed-item-0.0.6\node_modules\simple-encryptor\index.js:58:25)
	at Cpass.encode (c:\Users\jturner.BMA\.vscode\extensions\s-kainet.sharepoint-typed-item-0.0.6\node_modules\cpass\dist\Cpass.js:19:34)
	at Object.exports.convertAuthContextToSettings (c:\Users\jturner.BMA\.vscode\extensions\s-kainet.sharepoint-typed-item-0.0.6\node_modules\node-sp-auth-config\dist\utils\index.js:27:37)
	at exports.saveConfigOnDisk (c:\Users\jturner.BMA\.vscode\extensions\s-kainet.sharepoint-typed-item-0.0.6\node_modules\node-sp-auth-config\dist\utils\index.js:52:38)
	at new Promise (<anonymous>)
	at Object.exports.saveConfigOnDisk (c:\Users\jturner.BMA\.vscode\extensions\s-kainet.sharepoint-typed-item-0.0.6\node_modules\node-sp-auth-config\dist\utils\index.js:51:12)
	at AuthConfig.<anonymous> (c:\Users\jturner.BMA\.vscode\extensions\s-kainet.sharepoint-typed-item-0.0.6\node_modules\node-sp-auth-config\dist\index.js:83:44)
	at step (c:\Users\jturner.BMA\.vscode\extensions\s-kainet.sharepoint-typed-item-0.0.6\node_modules\node-sp-auth-config\dist\index.js:43:23)
	at Object.f [as next] (c:\Users\jturner.BMA\.vscode\extensions\s-kainet.sharepoint-typed-item-0.0.6\node_modules\node-sp-auth-config\dist\index.js:24:53)
	at fulfilled (c:\Users\jturner.BMA\.vscode\extensions\s-kainet.sharepoint-typed-item-0.0.6\node_modules\node-sp-auth-config\dist\index.js:15:58)

**Comment by s-KaiNet** [comment]
Hi Julie!
It looks like an issue with the encryption mechanism... I've never seen that before, I will take a closer look at the issue in a couple of days. Meanwhile, let me try to add the author of `cpass` library @koltyakov into the loop. Maybe he has some ideas about what's happening.   

BTW have you tried "clear credentials" command?

**Comment by rodneyviana** [comment]
I had the very same problem and I tried clearing authentication, resetting it and even installed the authentication package you mentioned. All to no avail

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by koltyakov** [comment]
Interesting one, this is an error message out from the standard/internal Node.js module - crypto.
It's not on Cpass end as it fails when calling internal methods.

I'd asked what Node.js version you're running on, not aware what VSCode uses internally, but considering an embed one, not the one installed on a machine.

Cpass's test suites are ok down to Node.js v6, for v4 tests fail, but who'd ever use Node.js v4 in the current reality and it's definitely should be a case with VSCode.

Can it be you're running x32 bit, maybe, just a guess as there are not other ideas at this tine. Cpass works on hundreds or thousands of installations never seen this error or issue requests before. Some googling leads to Electron, VSCode is Electron, so some Electron related aspect.

Guys, also, what version of VSCode you're running (ver, user/system install, 64/32 bit)?

**Comment by rodneyviana** [comment]
I am running 64-bit NodeJS version 10.6.3

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by s-KaiNet** [comment]
Could you also provide if you're on Mac or Windows?

**Comment by rodneyviana** [comment]
Windows 10

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by koltyakov** [comment]
Julie is on Win too based on paths in the error. Just checked with the latest VSCode version. On Mac, it works for me, on Win 10, x64 VSCode, User install, the same exception as in topic-starter message.

**Comment by s-KaiNet** [comment]
@rodneyviana 	did it work for you before?

**Comment by rodneyviana** [comment]
No. This was the first time I’ve tried to use it.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by koltyakov** [comment]
Was able to repro the same on Mac as well. It's related to VSCode migration to Electron 4 and internals with crypto library implementation (https://github.com/electron/electron/issues/16195#issuecomment-450152501). Looks the hash function used in encryptor library is not available in Electron 4 backend. Will keep you posted.

UPD: Was managed to make it work with Electron 4's BoringSSL by switching OpenSSL `aes256` alias to it's origin in BoringSSL (`aes-256-cbc`) in [simple-encryptor](https://github.com/sehrope/node-simple-encryptor) dependency. The switch is a monkey patch. Need to test something before pushing a PR to that library.

**Comment by koltyakov** [comment]
So, I've applied a fix in Cpass to support 4th and later Electron, or BoringSSL in particular.
Bumped node-sp-auth-config's dependencies.

Sergei, please update node-sp-auth-config or cpass in the extension when you are back from Stockholm. Safe travel!

**Comment by s-KaiNet** [comment]
Thank you so much, Andrew, for a super-fast reaction (as usual) and for the fix!   
I will update the extension as soon as I reach my PC :)

**Comment by s-KaiNet** [comment]
@juliemturner @rodneyviana 	a newer version 0.0.7 is available. Please make sure that you use the latest version by going to the extensions tab and verifying that there are no available updates. Additionally you can click on a gear icon and copy information about the extension (including installed version):  

![image](https://user-images.githubusercontent.com/10658276/64928595-22c06580-d823-11e9-9600-1cad20e8df19.png)

Could you please check that it works as expected right now?

**Comment by rodneyviana** [comment]
Thanks for doing this so quickly. I really appreciate it.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by s-KaiNet** [comment]
I'm closing the issue, please reopen if it's not fully fixed.
