### ISSUE TITLE
Error while resolving authentication class

### ISSUE THREAD

**Issue by snugam** [s-KaiNet/vscode-sp-typed-item#4]
Good day

Nice extension thank you.  I've used it for a while now.  We've recently shifted to multi-factor-authentication on office 365 and I am unable to rebuild the types, getting this error.  

`[Error - 13:30:50] An error occurred during the execution of the command 'sp-typed-item.generate': Error while resolving authentication class
[Error - 13:31:14] Error: Error while resolving authentication class
	at Function.resolve (c:\Users\####\.vscode\extensions\s-kainet.sharepoint-typed-item-0.0.7\node_modules\node-sp-auth\lib\src\auth\AuthResolverFactory.js:42:15)
	at Object.getAuth (c:\Users\####\.vscode\extensions\s-kainet.sharepoint-typed-item-0.0.7\node_modules\node-sp-auth\lib\src\index.js:8:54)
	at c:\Users\####\.vscode\extensions\s-kainet.sharepoint-typed-item-0.0.7\node_modules\sp-request\lib\src\core\SPRequest.js:40:20
	at Promise._execute (c:\Users\####\.vscode\extensions\s-kainet.sharepoint-typed-item-0.0.7\node_modules\bluebird\js\release\debuggability.js:313:9)
	at Promise._resolveFromExecutor (c:\Users\####\.vscode\extensions\s-kainet.sharepoint-typed-item-0.0.7\node_modules\bluebird\js\release\promise.js:483:18)
	at new Promise (c:\Users\####\.vscode\extensions\s-kainet.sharepoint-typed-item-0.0.7\node_modules\bluebird\js\release\promise.js:79:10)
	at coreRequest (c:\Users\####\.vscode\extensions\s-kainet.sharepoint-typed-item-0.0.7\node_modules\sp-request\lib\src\core\SPRequest.js:22:16)
	at spRequestFunc (c:\Users\####\.vscode\extensions\s-kainet.sharepoint-typed-item-0.0.7\node_modules\sp-request\lib\src\core\SPRequest.js:69:20)
	at Function.spRequestFunc.<computed> [as get] (c:\Users\####\.vscode\extensions\s-kainet.sharepoint-typed-item-0.0.7\node_modules\sp-request\lib\src\core\SPRequest.js:109:24)
	at SPService.<anonymous> (c:\Users\####\.vscode\extensions\s-kainet.sharepoint-typed-item-0.0.7\node_modules\sp-typed-item\lib\Common\SPService.js:24:35)
	at Generator.next (<anonymous>)
	at fulfilled (c:\Users\####\.vscode\extensions\s-kainet.sharepoint-typed-item-0.0.7\node_modules\sp-typed-item\lib\Common\SPService.js:5:58)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
[Error - 13:31:14] An error occurred during the execution of the command 'sp-typed-item.generate': Error while resolving authentication class`

**Comment by s-KaiNet** [comment]
Hi, 

for MFA you have two options: 
 - either use [app password](https://docs.microsoft.com/en-us/azure/active-directory/user-help/multi-factor-authentication-end-user-app-passwords) instead of you real password
 - or, if app passwords are not available, use add-in only authentication, for add-in only [you should configure](https://github.com/s-KaiNet/node-sp-auth/wiki/SharePoint-Online-addin-only-authentication) your client id and client secret

**Comment by snugam** [comment]
> Hi,
> 
> for MFA you have two options:
> 
> * either use [app password](https://docs.microsoft.com/en-us/azure/active-directory/user-help/multi-factor-authentication-end-user-app-passwords) instead of you real password
> * or, if app passwords are not available, use add-in only authentication, for add-in only [you should configure](https://github.com/s-KaiNet/node-sp-auth/wiki/SharePoint-Online-addin-only-authentication) your client id and client secret

Thank you, your suggestion worked - I was able to create an "app password". It is working fine now.   

Again, thank you for the prompt reply and a very useful extension.
